### ISSUE TITLE
Improve UI and add sounds.

### ISSUE THREAD

**Issue by Abhijay007** [Abhijay007/Mario-Run#3]
Improve UI and add sounds like Mario background music, jumping sound ( already added), and game over sound.
And By improving UI means display Game Over Banner Instead of an alert box.

**Comment by AlexARNcode** [comment]
Hi, I didn't have the time right now to do everything, but I did the jump sound you asked for. Created a PR for that.

**Comment by AlexARNcode** [comment]
Hi mate,
For background music, I think it would be a good idea to have a "START" button : 
https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

If not, it will not play automatically (considered as bad UX practice and will be blocked by browsers).

What do you think?

**Comment by Abhijay007** [comment]
> Hi mate,
> For background music, I think it would be a good idea to have a "START" button :
> https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
> 
> If not, it will not play automatically (considered as bad UX practice and will be blocked by browsers).
> 
> What do you think?

Yes, your suggestion is amazing I will definitely look forward to it. Or if you want to work on this Go ahead!!

Thanks for this amazing advice!!😊
